version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/api/src
    restart: always
    ports:
      - 4000:4000
    env_file:
      - ./.env.docker


  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'homework'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - 3306:3306
